### ISSUE TITLE
Variance ddof = 1 or 0 ?

### ISSUE THREAD

**Issue by loristns** [loristns/wgt#1]
https://github.com/loristns/wgt/blob/8b4cbe9f88a4de9ce0f6bff32467d61a325fa7dd/src/lib/ops/layerNorm.ts#L53C26-L53C49

**Comment by lorrding** [comment]
I think we good to merge

**Comment by loristns** [comment]
The implementation seems correct as is with regard to [GPT-2 original implementation](https://github.com/openai/gpt-2/blob/master/src/model.py#L28). Closing for now.
